### PR TITLE
Adding support for `GET /containers/` and `GET /containers?collections=something`

### PR DESCRIPTION
**Pull request by edyesed**
Hi,

I needed to query the `/containers` endpoint while passing in the collections query param. 

Go isn't really a primary language for me, so let me know if you'd like this implemented differently ( also feel free to swap it out for an implementation of your liking ).

### CODE REVIEW

**Comment by bls** [comment]
Thanks! 

EDIT: OK, so looking into this a little bit more, the API has changed quite a lot between 2.5 and the 18.x/19.x twistlock versions; it looks like you're working with the 2.5 API.

But we can't query by "collections" in 18.x + 

So as not to put something in that's immediately going to be a breaking API change, how about having just 1 method GetContainerList which takes a map of string that become query params?

The responses are also a bit different but we can easily add more fields to the struct later.

Diffs from docs are:

So... 2.5.x (with offset, limit) is paginated and 18.x is not.

The query params for 18.x + are:

hostname: (string)
Hosts is used to filter containers by host

id: (string)
IDs is used to filter container by container ID

image: (string)
Images is used to filter containers by image name

imageId: (string)
ImageIDs is used to filter containers by image ids

namespaces: (string)
Namespaces are the namespaces to filter

profileId: (string)
ProfileIDs is used to filter container by runtime profile ID

While the params for 2.5.x are:

search: (string)
Retrieves all scan reports where the search string matches the value of the container name, underlying fully qualified image name, hostname where the container runs, or startup command. Partial matches are supported. Therefore, the search string 'thor-1' would match 'thor-1.example.com'.

offset: (number)
Specifies the index of the first object (event, incident, etc) to return. The default value is 0. Use the 'offset' parameter with the 'limit' parameter to select specific objects in the collection. For example, to retrieve the second oldest object in the collection:

GET https://<CONSOLE>:8083/api/v1/<RESOURCE>?offset=1&limit=1
Where RESOURCE can be a top-level resource, such as images or containers.

limit: (number)
Specifies the maximum number of objects (events, incidents, etc) to return. If left unspecified, all objects are returned (optionally constrained by the 'offset' parameter). Use the 'limit' parameter with the 'offset' parameter to select specific objects in the collection. For example, to retrieve a single object (the oldest object in the collection):

GET https://<CONSOLE>:8083/api/v1/<RESOURCE>?offset=0&limit=1
Where RESOURCE can be a top-level resource, such as images or containers.

collections: (string)
Retrieves objects (events, incidents, etc) from the specified collections. This query parameter accepts a comma-delimited list of collections. When no collections are specified, objects in the default collection 'All' are returned. In other words, all objects would be returned.

**Comment by edyesed** [comment]
I think I can make that change pretty readily 👍 

Where are you seeing the API docs? I've been reading docs.twistlock.com... oh.. interesting. I now notice the API version in the url there. :eyes: 

In any event, I am pretty sure I can collapse to one method with the map argument as you've described.

**Comment by edyesed** [comment]
Second note: I'm using 19.7.X . While the collections queryparam isn't documented in the API, I used devtools to see what call the web-UI was making, and it included the undocumented collections queryparam 🙈. 

I'll move forward with the change as you've proposed, I very much appreciate the effort to be as flexible as possible ( and I also appreciate your constructive feedback 👍 )

**Comment by edyesed** [comment]
@bls,  LMK if this is in line with your vision. I've passed in a few of the documented query params that you listed above, and it seems to be functional with the 19.07 server to which I have access.

**Comment by bls** [comment]
Nice, thank you!

**Pull request merged**
